ElementList(Start)
ElementList(Need,"C17","cap_200mil","470n")
ElementSetAttr("C17","device","CAPACITOR")
ElementSetAttr("C17","manufacturer","unknown")
ElementSetAttr("C17","manufacturer_part_number","unknown")
ElementSetAttr("C17","vendor","unknown")
ElementSetAttr("C17","vendor_part_number","unknown")
ChangePinName("C17", 2, "2")
ChangePinName("C17", 1, "1")
ElementList(Need,"C15","cap_200mil","100n")
ElementSetAttr("C15","device","CAPACITOR")
ElementSetAttr("C15","manufacturer","unknown")
ElementSetAttr("C15","manufacturer_part_number","unknown")
ElementSetAttr("C15","vendor","unknown")
ElementSetAttr("C15","vendor_part_number","unknown")
ChangePinName("C15", 2, "2")
ChangePinName("C15", 1, "1")
ElementList(Need,"C18","tantal-100mil-1","22u")
ElementSetAttr("C18","device","CAPACITOR")
ElementSetAttr("C18","manufacturer","unknown")
ElementSetAttr("C18","manufacturer_part_number","unknown")
ElementSetAttr("C18","vendor","unknown")
ElementSetAttr("C18","vendor_part_number","unknown")
ChangePinName("C18", 2, "2")
ChangePinName("C18", 1, "1")
ElementList(Need,"R28","ACY300","47R")
ElementSetAttr("R28","device","RESISTOR")
ElementSetAttr("R28","manufacturer","unknown")
ElementSetAttr("R28","manufacturer_part_number","unknown")
ElementSetAttr("R28","vendor","unknown")
ElementSetAttr("R28","vendor_part_number","unknown")
ChangePinName("R28", 1, "1")
ChangePinName("R28", 2, "2")
ElementList(Need,"C16","cap_200mil","100n")
ElementSetAttr("C16","device","CAPACITOR")
ElementSetAttr("C16","manufacturer","unknown")
ElementSetAttr("C16","manufacturer_part_number","unknown")
ElementSetAttr("C16","vendor","unknown")
ElementSetAttr("C16","vendor_part_number","unknown")
ChangePinName("C16", 2, "2")
ChangePinName("C16", 1, "1")
ElementList(Need,"C14","tantal-100mil-1","1u")
ElementSetAttr("C14","device","CAPACITOR")
ElementSetAttr("C14","manufacturer","unknown")
ElementSetAttr("C14","manufacturer_part_number","unknown")
ElementSetAttr("C14","vendor","unknown")
ElementSetAttr("C14","vendor_part_number","unknown")
ChangePinName("C14", 2, "2")
ChangePinName("C14", 1, "1")
ElementList(Need,"B1","big-solder-pads-1","unknown")
ElementSetAttr("B1","device","BATTERY")
ElementSetAttr("B1","manufacturer","unknown")
ElementSetAttr("B1","manufacturer_part_number","unknown")
ElementSetAttr("B1","vendor","unknown")
ElementSetAttr("B1","vendor_part_number","unknown")
ChangePinName("B1", 2, "-")
ChangePinName("B1", 1, "+")
ElementList(Need,"D17","diode-standing-100mil-1","unknown")
ElementSetAttr("D17","device","DIODE")
ElementSetAttr("D17","manufacturer","unknown")
ElementSetAttr("D17","manufacturer_part_number","unknown")
ElementSetAttr("D17","vendor","unknown")
ElementSetAttr("D17","vendor_part_number","unknown")
ChangePinName("D17", 2, "2")
ChangePinName("D17", 1, "1")
ElementList(Need,"IN1","header-3pin-100mil-1","unknown")
ElementSetAttr("IN1","device","SERVO_CONNECTOR")
ElementSetAttr("IN1","manufacturer","unknown")
ElementSetAttr("IN1","manufacturer_part_number","unknown")
ElementSetAttr("IN1","vendor","unknown")
ElementSetAttr("IN1","vendor_part_number","unknown")
ChangePinName("IN1", 1, "GND")
ChangePinName("IN1", 2, "Vcc")
ChangePinName("IN1", 3, "SIG")
ElementList(Need,"Q5.2","TO220W","SOME_MOSFET")
ElementSetAttr("Q5.2","device","NMOS_TRANSISTOR")
ElementSetAttr("Q5.2","manufacturer","unknown")
ElementSetAttr("Q5.2","manufacturer_part_number","unknown")
ElementSetAttr("Q5.2","vendor","unknown")
ElementSetAttr("Q5.2","vendor_part_number","unknown")
ChangePinName("Q5.2", 3, "S")
ChangePinName("Q5.2", 2, "D")
ChangePinName("Q5.2", 1, "G")
ElementList(Need,"Q6.4","to251-1","IRLU8743PBF")
ElementSetAttr("Q6.4","device","NMOS_TRANSISTOR")
ElementSetAttr("Q6.4","manufacturer","unknown")
ElementSetAttr("Q6.4","manufacturer_part_number","unknown")
ElementSetAttr("Q6.4","vendor","unknown")
ElementSetAttr("Q6.4","vendor_part_number","unknown")
ChangePinName("Q6.4", 3, "S")
ChangePinName("Q6.4", 2, "D")
ChangePinName("Q6.4", 1, "G")
ElementList(Need,"Q6.3","to251-1","IRLU8743PBF")
ElementSetAttr("Q6.3","device","NMOS_TRANSISTOR")
ElementSetAttr("Q6.3","manufacturer","unknown")
ElementSetAttr("Q6.3","manufacturer_part_number","unknown")
ElementSetAttr("Q6.3","vendor","unknown")
ElementSetAttr("Q6.3","vendor_part_number","unknown")
ChangePinName("Q6.3", 3, "S")
ChangePinName("Q6.3", 2, "D")
ChangePinName("Q6.3", 1, "G")
ElementList(Need,"Q6.2","to251-1","IRLU8743PBF")
ElementSetAttr("Q6.2","device","NMOS_TRANSISTOR")
ElementSetAttr("Q6.2","manufacturer","unknown")
ElementSetAttr("Q6.2","manufacturer_part_number","unknown")
ElementSetAttr("Q6.2","vendor","unknown")
ElementSetAttr("Q6.2","vendor_part_number","unknown")
ChangePinName("Q6.2", 3, "S")
ChangePinName("Q6.2", 2, "D")
ChangePinName("Q6.2", 1, "G")
ElementList(Need,"Q6.1","to251-1","IRLU8743PBF")
ElementSetAttr("Q6.1","device","NMOS_TRANSISTOR")
ElementSetAttr("Q6.1","manufacturer","unknown")
ElementSetAttr("Q6.1","manufacturer_part_number","unknown")
ElementSetAttr("Q6.1","vendor","unknown")
ElementSetAttr("Q6.1","vendor_part_number","unknown")
ChangePinName("Q6.1", 3, "S")
ChangePinName("Q6.1", 2, "D")
ChangePinName("Q6.1", 1, "G")
ElementList(Need,"C7","tantal-100mil-1","100n")
ElementSetAttr("C7","device","CAPACITOR")
ElementSetAttr("C7","manufacturer","unknown")
ElementSetAttr("C7","manufacturer_part_number","unknown")
ElementSetAttr("C7","vendor","unknown")
ElementSetAttr("C7","vendor_part_number","unknown")
ChangePinName("C7", 2, "2")
ChangePinName("C7", 1, "1")
ElementList(Need,"U5","TO220W","LM2940")
ElementSetAttr("U5","device","VOLTAGE_REGULATOR")
ElementSetAttr("U5","manufacturer","unknown")
ElementSetAttr("U5","manufacturer_part_number","unknown")
ElementSetAttr("U5","vendor","unknown")
ElementSetAttr("U5","vendor_part_number","unknown")
ChangePinName("U5", 2, "GND")
ChangePinName("U5", 1, "Vi")
ChangePinName("U5", 3, "Vo")
ElementList(Need,"D1","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D1","device","DIODE")
ElementSetAttr("D1","manufacturer","unknown")
ElementSetAttr("D1","manufacturer_part_number","unknown")
ElementSetAttr("D1","vendor","unknown")
ElementSetAttr("D1","vendor_part_number","unknown")
ChangePinName("D1", 2, "2")
ChangePinName("D1", 1, "1")
ElementList(Need,"R1","ACY200","10k")
ElementSetAttr("R1","device","RESISTOR")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"R11","ACY200","10k")
ElementSetAttr("R11","device","RESISTOR")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"U1","DIP14","unknown")
ElementSetAttr("U1","device","LOGIC_IC")
ElementSetAttr("U1","manufacturer","unknown")
ElementSetAttr("U1","manufacturer_part_number","unknown")
ElementSetAttr("U1","vendor","unknown")
ElementSetAttr("U1","vendor_part_number","unknown")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 3, "i")
ChangePinName("U1", 4, "o")
ChangePinName("U1", 9, "i")
ChangePinName("U1", 8, "o")
ChangePinName("U1", 11, "i")
ChangePinName("U1", 10, "o")
ChangePinName("U1", 13, "i")
ChangePinName("U1", 12, "o")
ChangePinName("U1", 1, "i")
ChangePinName("U1", 2, "o")
ChangePinName("U1", 5, "i")
ChangePinName("U1", 6, "o")
ElementList(Need,"U2","DIP14","4001")
ElementSetAttr("U2","device","LOGIC_IC")
ElementSetAttr("U2","manufacturer","unknown")
ElementSetAttr("U2","manufacturer_part_number","unknown")
ElementSetAttr("U2","vendor","unknown")
ElementSetAttr("U2","vendor_part_number","unknown")
ChangePinName("U2", 7, "GND")
ChangePinName("U2", 14, "Vcc")
ChangePinName("U2", 3, "OUT")
ChangePinName("U2", 2, "IN2")
ChangePinName("U2", 1, "IN1")
ChangePinName("U2", 11, "OUT")
ChangePinName("U2", 13, "IN2")
ChangePinName("U2", 12, "IN1")
ChangePinName("U2", 10, "OUT")
ChangePinName("U2", 9, "IN2")
ChangePinName("U2", 8, "IN1")
ChangePinName("U2", 4, "OUT")
ChangePinName("U2", 6, "IN2")
ChangePinName("U2", 5, "IN1")
ElementList(Need,"D7","DIODE_LAY_300mil","unknown")
ElementSetAttr("D7","device","DIODE")
ElementSetAttr("D7","manufacturer","unknown")
ElementSetAttr("D7","manufacturer_part_number","unknown")
ElementSetAttr("D7","vendor","unknown")
ElementSetAttr("D7","vendor_part_number","unknown")
ChangePinName("D7", 2, "2")
ChangePinName("D7", 1, "1")
ElementList(Need,"R13","r-vert-100mil-1","47R")
ElementSetAttr("R13","device","RESISTOR")
ElementSetAttr("R13","manufacturer","unknown")
ElementSetAttr("R13","manufacturer_part_number","unknown")
ElementSetAttr("R13","vendor","unknown")
ElementSetAttr("R13","vendor_part_number","unknown")
ChangePinName("R13", 1, "1")
ChangePinName("R13", 2, "2")
ElementList(Need,"R12","r-vert-100mil-1","47R")
ElementSetAttr("R12","device","RESISTOR")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"R7","r-vert-100mil-1","120R")
ElementSetAttr("R7","device","RESISTOR")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"R8","ACY200","130R")
ElementSetAttr("R8","device","RESISTOR")
ElementSetAttr("R8","manufacturer","unknown")
ElementSetAttr("R8","manufacturer_part_number","unknown")
ElementSetAttr("R8","vendor","unknown")
ElementSetAttr("R8","vendor_part_number","unknown")
ChangePinName("R8", 1, "1")
ChangePinName("R8", 2, "2")
ElementList(Need,"U3","TO92-1","LM317")
ElementSetAttr("U3","device","VOLTAGE_REGULATOR")
ElementSetAttr("U3","manufacturer","unknown")
ElementSetAttr("U3","manufacturer_part_number","unknown")
ElementSetAttr("U3","vendor","unknown")
ElementSetAttr("U3","vendor_part_number","unknown")
ChangePinName("U3", 1, "Adj")
ChangePinName("U3", 3, "Vi")
ChangePinName("U3", 2, "Vo")
ElementList(Need,"Q4","TO92-1","BC557")
ElementSetAttr("Q4","device","TUP")
ElementSetAttr("Q4","manufacturer","unknown")
ElementSetAttr("Q4","manufacturer_part_number","unknown")
ElementSetAttr("Q4","vendor","unknown")
ElementSetAttr("Q4","vendor_part_number","unknown")
ChangePinName("Q4", 2, "B")
ChangePinName("Q4", 3, "C")
ChangePinName("Q4", 1, "E")
ElementList(Need,"Q2","TO92-1","BC557")
ElementSetAttr("Q2","device","TUP")
ElementSetAttr("Q2","manufacturer","unknown")
ElementSetAttr("Q2","manufacturer_part_number","unknown")
ElementSetAttr("Q2","vendor","unknown")
ElementSetAttr("Q2","vendor_part_number","unknown")
ChangePinName("Q2", 2, "B")
ChangePinName("Q2", 3, "C")
ChangePinName("Q2", 1, "E")
ElementList(Need,"R4","r-vert-100mil-1","100k")
ElementSetAttr("R4","device","RESISTOR")
ElementSetAttr("R4","manufacturer","unknown")
ElementSetAttr("R4","manufacturer_part_number","unknown")
ElementSetAttr("R4","vendor","unknown")
ElementSetAttr("R4","vendor_part_number","unknown")
ChangePinName("R4", 1, "1")
ChangePinName("R4", 2, "2")
ElementList(Need,"D11","DIODE_LAY_300mil","1N4937")
ElementSetAttr("D11","device","DIODE")
ElementSetAttr("D11","manufacturer","unknown")
ElementSetAttr("D11","manufacturer_part_number","unknown")
ElementSetAttr("D11","vendor","unknown")
ElementSetAttr("D11","vendor_part_number","unknown")
ChangePinName("D11", 2, "2")
ChangePinName("D11", 1, "1")
ElementList(Need,"C11","tantal-100mil-1","1u")
ElementSetAttr("C11","device","CAPACITOR")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "+")
ElementList(Need,"M1","big-solder-pads-1","unknown")
ElementSetAttr("M1","device","DC_MOTOR")
ElementSetAttr("M1","manufacturer","unknown")
ElementSetAttr("M1","manufacturer_part_number","unknown")
ElementSetAttr("M1","vendor","unknown")
ElementSetAttr("M1","vendor_part_number","unknown")
ChangePinName("M1", 2, "2")
ChangePinName("M1", 1, "1")
ElementList(Need,"Q5.1","TO220W","SOME_MOSFET")
ElementSetAttr("Q5.1","device","NMOS_TRANSISTOR")
ElementSetAttr("Q5.1","manufacturer","unknown")
ElementSetAttr("Q5.1","manufacturer_part_number","unknown")
ElementSetAttr("Q5.1","vendor","unknown")
ElementSetAttr("Q5.1","vendor_part_number","unknown")
ChangePinName("Q5.1", 3, "S")
ChangePinName("Q5.1", 2, "D")
ChangePinName("Q5.1", 1, "G")
ElementList(Need,"D6","diode-standing-100mil-1","unknown")
ElementSetAttr("D6","device","DIODE")
ElementSetAttr("D6","manufacturer","unknown")
ElementSetAttr("D6","manufacturer_part_number","unknown")
ElementSetAttr("D6","vendor","unknown")
ElementSetAttr("D6","vendor_part_number","unknown")
ChangePinName("D6", 2, "2")
ChangePinName("D6", 1, "1")
ElementList(Need,"C13","tantal-100mil-1","10u")
ElementSetAttr("C13","device","CAPACITOR")
ElementSetAttr("C13","manufacturer","unknown")
ElementSetAttr("C13","manufacturer_part_number","unknown")
ElementSetAttr("C13","vendor","unknown")
ElementSetAttr("C13","vendor_part_number","unknown")
ChangePinName("C13", 2, "2")
ChangePinName("C13", 1, "1")
ElementList(Need,"R9","r-vert-100mil-1","120k")
ElementSetAttr("R9","device","RESISTOR")
ElementSetAttr("R9","manufacturer","unknown")
ElementSetAttr("R9","manufacturer_part_number","unknown")
ElementSetAttr("R9","vendor","unknown")
ElementSetAttr("R9","vendor_part_number","unknown")
ChangePinName("R9", 1, "1")
ChangePinName("R9", 2, "2")
ElementList(Need,"D4","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D4","device","DIODE")
ElementSetAttr("D4","manufacturer","unknown")
ElementSetAttr("D4","manufacturer_part_number","unknown")
ElementSetAttr("D4","vendor","unknown")
ElementSetAttr("D4","vendor_part_number","unknown")
ChangePinName("D4", 2, "2")
ChangePinName("D4", 1, "1")
ElementList(Need,"U4","DIP8","LM358")
ElementSetAttr("U4","device","OPAMP")
ElementSetAttr("U4","manufacturer","unknown")
ElementSetAttr("U4","manufacturer_part_number","unknown")
ElementSetAttr("U4","vendor","unknown")
ElementSetAttr("U4","vendor_part_number","unknown")
ChangePinName("U4", 4, "GND")
ChangePinName("U4", 8, "Vcc")
ChangePinName("U4", 1, "1")
ChangePinName("U4", 2, "2")
ChangePinName("U4", 3, "3")
ChangePinName("U4", 7, "7")
ChangePinName("U4", 6, "6")
ChangePinName("U4", 5, "5")
ElementList(Need,"P2","pot_3362","50k")
ElementSetAttr("P2","device","VARIABLE_RESISTOR")
ElementSetAttr("P2","manufacturer","unknown")
ElementSetAttr("P2","manufacturer_part_number","unknown")
ElementSetAttr("P2","vendor","unknown")
ElementSetAttr("P2","vendor_part_number","unknown")
ChangePinName("P2", 3, "-")
ChangePinName("P2", 2, "-")
ChangePinName("P2", 1, "-")
ElementList(Need,"R10","r-vert-100mil-1","10k")
ElementSetAttr("R10","device","RESISTOR")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"R5","ACY200","10k")
ElementSetAttr("R5","device","RESISTOR")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"R6","ACY200","10k")
ElementSetAttr("R6","device","RESISTOR")
ElementSetAttr("R6","manufacturer","unknown")
ElementSetAttr("R6","manufacturer_part_number","unknown")
ElementSetAttr("R6","vendor","unknown")
ElementSetAttr("R6","vendor_part_number","unknown")
ChangePinName("R6", 1, "1")
ChangePinName("R6", 2, "2")
ElementList(Need,"D5","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D5","device","DIODE")
ElementSetAttr("D5","manufacturer","unknown")
ElementSetAttr("D5","manufacturer_part_number","unknown")
ElementSetAttr("D5","vendor","unknown")
ElementSetAttr("D5","vendor_part_number","unknown")
ChangePinName("D5", 2, "2")
ChangePinName("D5", 1, "1")
ElementList(Need,"D3","diode-standing-100mil-1","1N4148")
ElementSetAttr("D3","device","DIODE")
ElementSetAttr("D3","manufacturer","unknown")
ElementSetAttr("D3","manufacturer_part_number","unknown")
ElementSetAttr("D3","vendor","unknown")
ElementSetAttr("D3","vendor_part_number","unknown")
ChangePinName("D3", 2, "2")
ChangePinName("D3", 1, "1")
ElementList(Need,"D2","DIODE_LAY_300mil","1N4148")
ElementSetAttr("D2","device","DIODE")
ElementSetAttr("D2","manufacturer","unknown")
ElementSetAttr("D2","manufacturer_part_number","unknown")
ElementSetAttr("D2","vendor","unknown")
ElementSetAttr("D2","vendor_part_number","unknown")
ChangePinName("D2", 2, "2")
ChangePinName("D2", 1, "1")
ElementList(Need,"R3","ACY200","27k")
ElementSetAttr("R3","device","RESISTOR")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"P1","pot_3362","50k")
ElementSetAttr("P1","device","VARIABLE_RESISTOR")
ElementSetAttr("P1","manufacturer","unknown")
ElementSetAttr("P1","manufacturer_part_number","unknown")
ElementSetAttr("P1","vendor","unknown")
ElementSetAttr("P1","vendor_part_number","unknown")
ChangePinName("P1", 3, "-")
ChangePinName("P1", 2, "-")
ChangePinName("P1", 1, "-")
ElementList(Need,"R2","ACY300","200k")
ElementSetAttr("R2","device","RESISTOR")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"C6","cap_200mil","220n")
ElementSetAttr("C6","device","CAPACITOR")
ElementSetAttr("C6","manufacturer","unknown")
ElementSetAttr("C6","manufacturer_part_number","unknown")
ElementSetAttr("C6","vendor","unknown")
ElementSetAttr("C6","vendor_part_number","unknown")
ChangePinName("C6", 2, "2")
ChangePinName("C6", 1, "1")
ElementList(Need,"C12","cap_200mil","100n")
ElementSetAttr("C12","device","CAPACITOR")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"C8","cap_200mil","100n")
ElementSetAttr("C8","device","CAPACITOR")
ElementSetAttr("C8","manufacturer","unknown")
ElementSetAttr("C8","manufacturer_part_number","unknown")
ElementSetAttr("C8","vendor","unknown")
ElementSetAttr("C8","vendor_part_number","unknown")
ChangePinName("C8", 2, "2")
ChangePinName("C8", 1, "1")
ElementList(Need,"C3","cap_200mil","22n")
ElementSetAttr("C3","device","CAPACITOR")
ElementSetAttr("C3","manufacturer","unknown")
ElementSetAttr("C3","manufacturer_part_number","unknown")
ElementSetAttr("C3","vendor","unknown")
ElementSetAttr("C3","vendor_part_number","unknown")
ChangePinName("C3", 2, "2")
ChangePinName("C3", 1, "1")
ElementList(Need,"C2","cap_200mil","10n")
ElementSetAttr("C2","device","CAPACITOR")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"C1","cap_200mil","100n")
ElementSetAttr("C1","device","CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 1, "1")
ChangePinName("C1", 2, "2")
ElementList(Need,"D10","diode-standing-100mil-1","1N4002")
ElementSetAttr("D10","device","DIODE")
ElementSetAttr("D10","manufacturer","unknown")
ElementSetAttr("D10","manufacturer_part_number","unknown")
ElementSetAttr("D10","vendor","unknown")
ElementSetAttr("D10","vendor_part_number","unknown")
ChangePinName("D10", 2, "2")
ChangePinName("D10", 1, "1")
ElementList(Need,"D9","diode-standing-100mil-45d-1","1N4002")
ElementSetAttr("D9","device","DIODE")
ElementSetAttr("D9","manufacturer","unknown")
ElementSetAttr("D9","manufacturer_part_number","unknown")
ElementSetAttr("D9","vendor","unknown")
ElementSetAttr("D9","vendor_part_number","unknown")
ChangePinName("D9", 2, "2")
ChangePinName("D9", 1, "1")
ElementList(Need,"D8","DIODE_LAY_300mil","1N4002")
ElementSetAttr("D8","device","DIODE")
ElementSetAttr("D8","manufacturer","unknown")
ElementSetAttr("D8","manufacturer_part_number","unknown")
ElementSetAttr("D8","vendor","unknown")
ElementSetAttr("D8","vendor_part_number","unknown")
ChangePinName("D8", 2, "2")
ChangePinName("D8", 1, "1")
ElementList(Need,"Q3","TO92-1","BC547")
ElementSetAttr("Q3","device","TUN")
ElementSetAttr("Q3","manufacturer","unknown")
ElementSetAttr("Q3","manufacturer_part_number","unknown")
ElementSetAttr("Q3","vendor","unknown")
ElementSetAttr("Q3","vendor_part_number","unknown")
ChangePinName("Q3", 2, "B")
ChangePinName("Q3", 1, "E")
ChangePinName("Q3", 3, "C")
ElementList(Need,"C10","tantal-100mil-1","1u")
ElementSetAttr("C10","device","CAPACITOR")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "+")
ElementList(Need,"C9","cap_200mil","100n")
ElementSetAttr("C9","device","CAPACITOR")
ElementSetAttr("C9","manufacturer","unknown")
ElementSetAttr("C9","manufacturer_part_number","unknown")
ElementSetAttr("C9","vendor","unknown")
ElementSetAttr("C9","vendor_part_number","unknown")
ChangePinName("C9", 2, "2")
ChangePinName("C9", 1, "1")
ElementList(Need,"Q1","TO92-1","BC547")
ElementSetAttr("Q1","device","TUN")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 2, "B")
ChangePinName("Q1", 1, "E")
ChangePinName("Q1", 3, "C")
ElementList(Need,"R14","ACY200","10k")
ElementSetAttr("R14","device","RESISTOR")
ElementSetAttr("R14","manufacturer","unknown")
ElementSetAttr("R14","manufacturer_part_number","unknown")
ElementSetAttr("R14","vendor","unknown")
ElementSetAttr("R14","vendor_part_number","unknown")
ChangePinName("R14", 1, "1")
ChangePinName("R14", 2, "2")
ElementList(Done)
