ElementList(Start)
ElementList(Need,"C6","cap_200mil","100n")
ElementSetAttr("C6","device","CAPACITOR")
ElementSetAttr("C6","manufacturer","unknown")
ElementSetAttr("C6","manufacturer_part_number","unknown")
ElementSetAttr("C6","vendor","unknown")
ElementSetAttr("C6","vendor_part_number","unknown")
ChangePinName("C6", 2, "2")
ChangePinName("C6", 1, "1")
ElementList(Need,"D8","$(Footprint)","1N4148")
ElementSetAttr("D8","device","DIODE")
ElementSetAttr("D8","manufacturer","unknown")
ElementSetAttr("D8","manufacturer_part_number","unknown")
ElementSetAttr("D8","vendor","unknown")
ElementSetAttr("D8","vendor_part_number","unknown")
ChangePinName("D8", 2, "2")
ChangePinName("D8", 1, "1")
ElementList(Need,"R16","ACY300","4k7")
ElementSetAttr("R16","device","RESISTOR")
ElementSetAttr("R16","manufacturer","unknown")
ElementSetAttr("R16","manufacturer_part_number","unknown")
ElementSetAttr("R16","vendor","unknown")
ElementSetAttr("R16","vendor_part_number","unknown")
ChangePinName("R16", 1, "1")
ChangePinName("R16", 2, "2")
ElementList(Need,"R19","ACY300","47R")
ElementSetAttr("R19","device","RESISTOR")
ElementSetAttr("R19","manufacturer","unknown")
ElementSetAttr("R19","manufacturer_part_number","unknown")
ElementSetAttr("R19","vendor","unknown")
ElementSetAttr("R19","vendor_part_number","unknown")
ChangePinName("R19", 1, "1")
ChangePinName("R19", 2, "2")
ElementList(Need,"R18","ACY300","47R")
ElementSetAttr("R18","device","RESISTOR")
ElementSetAttr("R18","manufacturer","unknown")
ElementSetAttr("R18","manufacturer_part_number","unknown")
ElementSetAttr("R18","vendor","unknown")
ElementSetAttr("R18","vendor_part_number","unknown")
ChangePinName("R18", 1, "1")
ChangePinName("R18", 2, "2")
ElementList(Need,"R9","ACY300","100k")
ElementSetAttr("R9","device","RESISTOR")
ElementSetAttr("R9","manufacturer","unknown")
ElementSetAttr("R9","manufacturer_part_number","unknown")
ElementSetAttr("R9","vendor","unknown")
ElementSetAttr("R9","vendor_part_number","unknown")
ChangePinName("R9", 1, "1")
ChangePinName("R9", 2, "2")
ElementList(Need,"C15","$(footprint)","1u")
ElementSetAttr("C15","device","CAPACITOR")
ElementSetAttr("C15","manufacturer","unknown")
ElementSetAttr("C15","manufacturer_part_number","unknown")
ElementSetAttr("C15","vendor","unknown")
ElementSetAttr("C15","vendor_part_number","unknown")
ChangePinName("C15", 2, "2")
ChangePinName("C15", 1, "1")
ElementList(Need,"D17","$(Footprint)","unknown")
ElementSetAttr("D17","device","DIODE")
ElementSetAttr("D17","manufacturer","unknown")
ElementSetAttr("D17","manufacturer_part_number","unknown")
ElementSetAttr("D17","vendor","unknown")
ElementSetAttr("D17","vendor_part_number","unknown")
ChangePinName("D17", 2, "2")
ChangePinName("D17", 1, "1")
ElementList(Need,"R28","ACY300","47R")
ElementSetAttr("R28","device","RESISTOR")
ElementSetAttr("R28","manufacturer","unknown")
ElementSetAttr("R28","manufacturer_part_number","unknown")
ElementSetAttr("R28","vendor","unknown")
ElementSetAttr("R28","vendor_part_number","unknown")
ChangePinName("R28", 1, "1")
ChangePinName("R28", 2, "2")
ElementList(Need,"B1","unknown","unknown")
ElementSetAttr("B1","device","BATTERY")
ElementSetAttr("B1","manufacturer","unknown")
ElementSetAttr("B1","manufacturer_part_number","unknown")
ElementSetAttr("B1","vendor","unknown")
ElementSetAttr("B1","vendor_part_number","unknown")
ChangePinName("B1", 2, "-")
ChangePinName("B1", 1, "+")
ElementList(Need,"D14","$(Footprint)","1N4762")
ElementSetAttr("D14","device","DIODE")
ElementSetAttr("D14","manufacturer","unknown")
ElementSetAttr("D14","manufacturer_part_number","unknown")
ElementSetAttr("D14","vendor","unknown")
ElementSetAttr("D14","vendor_part_number","unknown")
ChangePinName("D14", 2, "2")
ChangePinName("D14", 1, "1")
ElementList(Need,"Q9","unknown","BD139")
ElementSetAttr("Q9","device","TUN")
ElementSetAttr("Q9","manufacturer","unknown")
ElementSetAttr("Q9","manufacturer_part_number","unknown")
ElementSetAttr("Q9","vendor","unknown")
ElementSetAttr("Q9","vendor_part_number","unknown")
ChangePinName("Q9", 2, "B")
ChangePinName("Q9", 1, "E")
ChangePinName("Q9", 3, "C")
ElementList(Need,"D15","$(Footprint)","unknown")
ElementSetAttr("D15","device","DIODE")
ElementSetAttr("D15","manufacturer","unknown")
ElementSetAttr("D15","manufacturer_part_number","unknown")
ElementSetAttr("D15","vendor","unknown")
ElementSetAttr("D15","vendor_part_number","unknown")
ChangePinName("D15", 2, "2")
ChangePinName("D15", 1, "1")
ElementList(Need,"C12","$(Footprint)","100n")
ElementSetAttr("C12","device","CAPACITOR")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"R20","ACY300","150R")
ElementSetAttr("R20","device","RESISTOR")
ElementSetAttr("R20","manufacturer","unknown")
ElementSetAttr("R20","manufacturer_part_number","unknown")
ElementSetAttr("R20","vendor","unknown")
ElementSetAttr("R20","vendor_part_number","unknown")
ChangePinName("R20", 1, "1")
ChangePinName("R20", 2, "2")
ElementList(Need,"R11","ACY300","10k")
ElementSetAttr("R11","device","RESISTOR")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"Q4","TO92-1","BC547")
ElementSetAttr("Q4","device","TUN")
ElementSetAttr("Q4","manufacturer","unknown")
ElementSetAttr("Q4","manufacturer_part_number","unknown")
ElementSetAttr("Q4","vendor","unknown")
ElementSetAttr("Q4","vendor_part_number","unknown")
ChangePinName("Q4", 2, "B")
ChangePinName("Q4", 1, "E")
ChangePinName("Q4", 3, "C")
ElementList(Need,"C9","$(footprint)","1u")
ElementSetAttr("C9","device","CAPACITOR")
ElementSetAttr("C9","manufacturer","unknown")
ElementSetAttr("C9","manufacturer_part_number","unknown")
ElementSetAttr("C9","vendor","unknown")
ElementSetAttr("C9","vendor_part_number","unknown")
ChangePinName("C9", 2, "2")
ChangePinName("C9", 1, "+")
ElementList(Need,"M1","unknown","unknown")
ElementSetAttr("M1","device","DC_MOTOR")
ElementSetAttr("M1","manufacturer","unknown")
ElementSetAttr("M1","manufacturer_part_number","unknown")
ElementSetAttr("M1","vendor","unknown")
ElementSetAttr("M1","vendor_part_number","unknown")
ChangePinName("M1", 2, "2")
ChangePinName("M1", 1, "1")
ElementList(Need,"Q28","unknown","SOME_MOSFET")
ElementSetAttr("Q28","device","NMOS_TRANSISTOR")
ElementSetAttr("Q28","manufacturer","unknown")
ElementSetAttr("Q28","manufacturer_part_number","unknown")
ElementSetAttr("Q28","vendor","unknown")
ElementSetAttr("Q28","vendor_part_number","unknown")
ChangePinName("Q28", 3, "S")
ChangePinName("Q28", 1, "D")
ChangePinName("Q28", 2, "G")
ElementList(Need,"Q27","unknown","SOME_MOSFET")
ElementSetAttr("Q27","device","NMOS_TRANSISTOR")
ElementSetAttr("Q27","manufacturer","unknown")
ElementSetAttr("Q27","manufacturer_part_number","unknown")
ElementSetAttr("Q27","vendor","unknown")
ElementSetAttr("Q27","vendor_part_number","unknown")
ChangePinName("Q27", 3, "S")
ChangePinName("Q27", 1, "D")
ChangePinName("Q27", 2, "G")
ElementList(Need,"Q26","unknown","SOME_MOSFET")
ElementSetAttr("Q26","device","NMOS_TRANSISTOR")
ElementSetAttr("Q26","manufacturer","unknown")
ElementSetAttr("Q26","manufacturer_part_number","unknown")
ElementSetAttr("Q26","vendor","unknown")
ElementSetAttr("Q26","vendor_part_number","unknown")
ChangePinName("Q26", 3, "S")
ChangePinName("Q26", 1, "D")
ChangePinName("Q26", 2, "G")
ElementList(Need,"Q25","unknown","SOME_MOSFET")
ElementSetAttr("Q25","device","NMOS_TRANSISTOR")
ElementSetAttr("Q25","manufacturer","unknown")
ElementSetAttr("Q25","manufacturer_part_number","unknown")
ElementSetAttr("Q25","vendor","unknown")
ElementSetAttr("Q25","vendor_part_number","unknown")
ChangePinName("Q25", 3, "S")
ChangePinName("Q25", 1, "D")
ChangePinName("Q25", 2, "G")
ElementList(Need,"Q24","unknown","SOME_MOSFET")
ElementSetAttr("Q24","device","NMOS_TRANSISTOR")
ElementSetAttr("Q24","manufacturer","unknown")
ElementSetAttr("Q24","manufacturer_part_number","unknown")
ElementSetAttr("Q24","vendor","unknown")
ElementSetAttr("Q24","vendor_part_number","unknown")
ChangePinName("Q24", 3, "S")
ChangePinName("Q24", 1, "D")
ChangePinName("Q24", 2, "G")
ElementList(Need,"Q23","unknown","SOME_MOSFET")
ElementSetAttr("Q23","device","NMOS_TRANSISTOR")
ElementSetAttr("Q23","manufacturer","unknown")
ElementSetAttr("Q23","manufacturer_part_number","unknown")
ElementSetAttr("Q23","vendor","unknown")
ElementSetAttr("Q23","vendor_part_number","unknown")
ChangePinName("Q23", 3, "S")
ChangePinName("Q23", 1, "D")
ChangePinName("Q23", 2, "G")
ElementList(Need,"Q22","unknown","SOME_MOSFET")
ElementSetAttr("Q22","device","NMOS_TRANSISTOR")
ElementSetAttr("Q22","manufacturer","unknown")
ElementSetAttr("Q22","manufacturer_part_number","unknown")
ElementSetAttr("Q22","vendor","unknown")
ElementSetAttr("Q22","vendor_part_number","unknown")
ChangePinName("Q22", 3, "S")
ChangePinName("Q22", 1, "D")
ChangePinName("Q22", 2, "G")
ElementList(Need,"Q21","unknown","SOME_MOSFET")
ElementSetAttr("Q21","device","NMOS_TRANSISTOR")
ElementSetAttr("Q21","manufacturer","unknown")
ElementSetAttr("Q21","manufacturer_part_number","unknown")
ElementSetAttr("Q21","vendor","unknown")
ElementSetAttr("Q21","vendor_part_number","unknown")
ChangePinName("Q21", 3, "S")
ChangePinName("Q21", 1, "D")
ChangePinName("Q21", 2, "G")
ElementList(Need,"Q20","unknown","SOME_MOSFET")
ElementSetAttr("Q20","device","NMOS_TRANSISTOR")
ElementSetAttr("Q20","manufacturer","unknown")
ElementSetAttr("Q20","manufacturer_part_number","unknown")
ElementSetAttr("Q20","vendor","unknown")
ElementSetAttr("Q20","vendor_part_number","unknown")
ChangePinName("Q20", 3, "S")
ChangePinName("Q20", 1, "D")
ChangePinName("Q20", 2, "G")
ElementList(Need,"D10","$(Footprint)","unknown")
ElementSetAttr("D10","device","DIODE")
ElementSetAttr("D10","manufacturer","unknown")
ElementSetAttr("D10","manufacturer_part_number","unknown")
ElementSetAttr("D10","vendor","unknown")
ElementSetAttr("D10","vendor_part_number","unknown")
ChangePinName("D10", 2, "2")
ChangePinName("D10", 1, "1")
ElementList(Need,"D9","$(Footprint)","unknown")
ElementSetAttr("D9","device","DIODE")
ElementSetAttr("D9","manufacturer","unknown")
ElementSetAttr("D9","manufacturer_part_number","unknown")
ElementSetAttr("D9","vendor","unknown")
ElementSetAttr("D9","vendor_part_number","unknown")
ChangePinName("D9", 2, "2")
ChangePinName("D9", 1, "1")
ElementList(Need,"C10","$(footprint)","10u")
ElementSetAttr("C10","device","CAPACITOR")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "1")
ElementList(Need,"R15","ACY300","120k")
ElementSetAttr("R15","device","RESISTOR")
ElementSetAttr("R15","manufacturer","unknown")
ElementSetAttr("R15","manufacturer_part_number","unknown")
ElementSetAttr("R15","vendor","unknown")
ElementSetAttr("R15","vendor_part_number","unknown")
ChangePinName("R15", 1, "1")
ChangePinName("R15", 2, "2")
ElementList(Need,"R10","ACY300","10k")
ElementSetAttr("R10","device","RESISTOR")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"D7","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D7","device","DIODE")
ElementSetAttr("D7","manufacturer","unknown")
ElementSetAttr("D7","manufacturer_part_number","unknown")
ElementSetAttr("D7","vendor","unknown")
ElementSetAttr("D7","vendor_part_number","unknown")
ChangePinName("D7", 2, "2")
ChangePinName("D7", 1, "1")
ElementList(Need,"U2","DIP8","LM358")
ElementSetAttr("U2","device","OPAMP")
ElementSetAttr("U2","manufacturer","unknown")
ElementSetAttr("U2","manufacturer_part_number","unknown")
ElementSetAttr("U2","vendor","unknown")
ElementSetAttr("U2","vendor_part_number","unknown")
ChangePinName("U2", 4, "GND")
ChangePinName("U2", 7, "Vcc")
ChangePinName("U2", 1, "1")
ChangePinName("U2", 2, "2")
ChangePinName("U2", 3, "3")
ChangePinName("U2", 7, "Vcc")
ChangePinName("U2", 6, "6")
ChangePinName("U2", 5, "5")
ElementList(Need,"P2","POT_LAYING","50k")
ElementSetAttr("P2","device","VARIABLE_RESISTOR")
ElementSetAttr("P2","manufacturer","unknown")
ElementSetAttr("P2","manufacturer_part_number","unknown")
ElementSetAttr("P2","vendor","unknown")
ElementSetAttr("P2","vendor_part_number","unknown")
ChangePinName("P2", 3, "-")
ChangePinName("P2", 2, "-")
ChangePinName("P2", 1, "-")
ElementList(Need,"R13","ACY300","10k")
ElementSetAttr("R13","device","RESISTOR")
ElementSetAttr("R13","manufacturer","unknown")
ElementSetAttr("R13","manufacturer_part_number","unknown")
ElementSetAttr("R13","vendor","unknown")
ElementSetAttr("R13","vendor_part_number","unknown")
ChangePinName("R13", 1, "1")
ChangePinName("R13", 2, "2")
ElementList(Need,"R17","ACY300","1k")
ElementSetAttr("R17","device","RESISTOR")
ElementSetAttr("R17","manufacturer","unknown")
ElementSetAttr("R17","manufacturer_part_number","unknown")
ElementSetAttr("R17","vendor","unknown")
ElementSetAttr("R17","vendor_part_number","unknown")
ChangePinName("R17", 1, "1")
ChangePinName("R17", 2, "2")
ElementList(Need,"R12","ACY300","1k")
ElementSetAttr("R12","device","RESISTOR")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"D6","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D6","device","DIODE")
ElementSetAttr("D6","manufacturer","unknown")
ElementSetAttr("D6","manufacturer_part_number","unknown")
ElementSetAttr("D6","vendor","unknown")
ElementSetAttr("D6","vendor_part_number","unknown")
ChangePinName("D6", 2, "2")
ChangePinName("D6", 1, "1")
ElementList(Need,"Q3","TO92-1","BC547")
ElementSetAttr("Q3","device","TUN")
ElementSetAttr("Q3","manufacturer","unknown")
ElementSetAttr("Q3","manufacturer_part_number","unknown")
ElementSetAttr("Q3","vendor","unknown")
ElementSetAttr("Q3","vendor_part_number","unknown")
ChangePinName("Q3", 2, "B")
ChangePinName("Q3", 1, "E")
ChangePinName("Q3", 3, "C")
ElementList(Need,"R8","ACY300","100k")
ElementSetAttr("R8","device","RESISTOR")
ElementSetAttr("R8","manufacturer","unknown")
ElementSetAttr("R8","manufacturer_part_number","unknown")
ElementSetAttr("R8","vendor","unknown")
ElementSetAttr("R8","vendor_part_number","unknown")
ChangePinName("R8", 1, "1")
ChangePinName("R8", 2, "2")
ElementList(Need,"D3","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D3","device","DIODE")
ElementSetAttr("D3","manufacturer","unknown")
ElementSetAttr("D3","manufacturer_part_number","unknown")
ElementSetAttr("D3","vendor","unknown")
ElementSetAttr("D3","vendor_part_number","unknown")
ChangePinName("D3", 2, "2")
ChangePinName("D3", 1, "1")
ElementList(Need,"D2","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D2","device","DIODE")
ElementSetAttr("D2","manufacturer","unknown")
ElementSetAttr("D2","manufacturer_part_number","unknown")
ElementSetAttr("D2","vendor","unknown")
ElementSetAttr("D2","vendor_part_number","unknown")
ChangePinName("D2", 2, "2")
ChangePinName("D2", 1, "1")
ElementList(Need,"D4","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D4","device","DIODE")
ElementSetAttr("D4","manufacturer","unknown")
ElementSetAttr("D4","manufacturer_part_number","unknown")
ElementSetAttr("D4","vendor","unknown")
ElementSetAttr("D4","vendor_part_number","unknown")
ChangePinName("D4", 2, "2")
ChangePinName("D4", 1, "1")
ElementList(Need,"D5","DIODE_LAY_200mil","1N4148")
ElementSetAttr("D5","device","DIODE")
ElementSetAttr("D5","manufacturer","unknown")
ElementSetAttr("D5","manufacturer_part_number","unknown")
ElementSetAttr("D5","vendor","unknown")
ElementSetAttr("D5","vendor_part_number","unknown")
ChangePinName("D5", 2, "2")
ChangePinName("D5", 1, "1")
ElementList(Need,"R5","ACY300","27k")
ElementSetAttr("R5","device","RESISTOR")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"P1","POT_LAYING","50k")
ElementSetAttr("P1","device","VARIABLE_RESISTOR")
ElementSetAttr("P1","manufacturer","unknown")
ElementSetAttr("P1","manufacturer_part_number","unknown")
ElementSetAttr("P1","vendor","unknown")
ElementSetAttr("P1","vendor_part_number","unknown")
ChangePinName("P1", 3, "-")
ChangePinName("P1", 2, "-")
ChangePinName("P1", 1, "-")
ElementList(Need,"D1","DIODE_LAY_300mil","1N4148")
ElementSetAttr("D1","device","DIODE")
ElementSetAttr("D1","manufacturer","unknown")
ElementSetAttr("D1","manufacturer_part_number","unknown")
ElementSetAttr("D1","vendor","unknown")
ElementSetAttr("D1","vendor_part_number","unknown")
ChangePinName("D1", 2, "2")
ChangePinName("D1", 1, "1")
ElementList(Need,"R3","ACY300","200k")
ElementSetAttr("R3","device","RESISTOR")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"R7","ACY300","4k7")
ElementSetAttr("R7","device","RESISTOR")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"Q1","TO92-1","BC547")
ElementSetAttr("Q1","device","TUN")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 2, "B")
ChangePinName("Q1", 1, "E")
ChangePinName("Q1", 3, "C")
ElementList(Need,"R4","ACY300","10k")
ElementSetAttr("R4","device","RESISTOR")
ElementSetAttr("R4","manufacturer","unknown")
ElementSetAttr("R4","manufacturer_part_number","unknown")
ElementSetAttr("R4","vendor","unknown")
ElementSetAttr("R4","vendor_part_number","unknown")
ChangePinName("R4", 1, "1")
ChangePinName("R4", 2, "2")
ElementList(Need,"R1","ACY300","10k")
ElementSetAttr("R1","device","RESISTOR")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"R2","ACY300","470R")
ElementSetAttr("R2","device","RESISTOR")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"Q2","TO92-1","BC547")
ElementSetAttr("Q2","device","TUN")
ElementSetAttr("Q2","manufacturer","unknown")
ElementSetAttr("Q2","manufacturer_part_number","unknown")
ElementSetAttr("Q2","vendor","unknown")
ElementSetAttr("Q2","vendor_part_number","unknown")
ChangePinName("Q2", 2, "B")
ChangePinName("Q2", 1, "E")
ChangePinName("Q2", 3, "C")
ElementList(Need,"C4","$(Footprint)","220n")
ElementSetAttr("C4","device","CAPACITOR")
ElementSetAttr("C4","manufacturer","unknown")
ElementSetAttr("C4","manufacturer_part_number","unknown")
ElementSetAttr("C4","vendor","unknown")
ElementSetAttr("C4","vendor_part_number","unknown")
ChangePinName("C4", 2, "2")
ChangePinName("C4", 1, "1")
ElementList(Need,"C11","cap_200mil","100n")
ElementSetAttr("C11","device","CAPACITOR")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "1")
ElementList(Need,"C5","$(Footprint)","100n")
ElementSetAttr("C5","device","CAPACITOR")
ElementSetAttr("C5","manufacturer","unknown")
ElementSetAttr("C5","manufacturer_part_number","unknown")
ElementSetAttr("C5","vendor","unknown")
ElementSetAttr("C5","vendor_part_number","unknown")
ChangePinName("C5", 2, "2")
ChangePinName("C5", 1, "1")
ElementList(Need,"C3","cap_200mil","22n")
ElementSetAttr("C3","device","CAPACITOR")
ElementSetAttr("C3","manufacturer","unknown")
ElementSetAttr("C3","manufacturer_part_number","unknown")
ElementSetAttr("C3","vendor","unknown")
ElementSetAttr("C3","vendor_part_number","unknown")
ChangePinName("C3", 2, "2")
ChangePinName("C3", 1, "1")
ElementList(Need,"C2","cap_200mil","10n")
ElementSetAttr("C2","device","CAPACITOR")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"C1","cap_200mil","100n")
ElementSetAttr("C1","device","CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "2")
ChangePinName("C1", 1, "1")
ElementList(Need,"D13","DIODE_LAY_300mil","1N4002")
ElementSetAttr("D13","device","DIODE")
ElementSetAttr("D13","manufacturer","unknown")
ElementSetAttr("D13","manufacturer_part_number","unknown")
ElementSetAttr("D13","vendor","unknown")
ElementSetAttr("D13","vendor_part_number","unknown")
ChangePinName("D13", 2, "2")
ChangePinName("D13", 1, "1")
ElementList(Need,"D12","DIODE_LAY_300mil","1N4002")
ElementSetAttr("D12","device","DIODE")
ElementSetAttr("D12","manufacturer","unknown")
ElementSetAttr("D12","manufacturer_part_number","unknown")
ElementSetAttr("D12","vendor","unknown")
ElementSetAttr("D12","vendor_part_number","unknown")
ChangePinName("D12", 2, "2")
ChangePinName("D12", 1, "1")
ElementList(Need,"D11","DIODE_LAY_300mil","1N4002")
ElementSetAttr("D11","device","DIODE")
ElementSetAttr("D11","manufacturer","unknown")
ElementSetAttr("D11","manufacturer_part_number","unknown")
ElementSetAttr("D11","vendor","unknown")
ElementSetAttr("D11","vendor_part_number","unknown")
ChangePinName("D11", 2, "2")
ChangePinName("D11", 1, "1")
ElementList(Need,"Q7","TO92-1","BC547")
ElementSetAttr("Q7","device","TUN")
ElementSetAttr("Q7","manufacturer","unknown")
ElementSetAttr("Q7","manufacturer_part_number","unknown")
ElementSetAttr("Q7","vendor","unknown")
ElementSetAttr("Q7","vendor_part_number","unknown")
ChangePinName("Q7", 2, "B")
ChangePinName("Q7", 1, "E")
ChangePinName("Q7", 3, "C")
ElementList(Need,"Q8","TO92-1","BC557")
ElementSetAttr("Q8","device","TUP")
ElementSetAttr("Q8","manufacturer","unknown")
ElementSetAttr("Q8","manufacturer_part_number","unknown")
ElementSetAttr("Q8","vendor","unknown")
ElementSetAttr("Q8","vendor_part_number","unknown")
ChangePinName("Q8", 2, "B")
ChangePinName("Q8", 1, "C")
ChangePinName("Q8", 3, "E")
ElementList(Need,"C8","$(footprint)","1u")
ElementSetAttr("C8","device","CAPACITOR")
ElementSetAttr("C8","manufacturer","unknown")
ElementSetAttr("C8","manufacturer_part_number","unknown")
ElementSetAttr("C8","vendor","unknown")
ElementSetAttr("C8","vendor_part_number","unknown")
ChangePinName("C8", 2, "2")
ChangePinName("C8", 1, "+")
ElementList(Need,"C7","$(Footprint)","100n")
ElementSetAttr("C7","device","CAPACITOR")
ElementSetAttr("C7","manufacturer","unknown")
ElementSetAttr("C7","manufacturer_part_number","unknown")
ElementSetAttr("C7","vendor","unknown")
ElementSetAttr("C7","vendor_part_number","unknown")
ChangePinName("C7", 2, "2")
ChangePinName("C7", 1, "1")
ElementList(Need,"Q6","TO92-1","BC557")
ElementSetAttr("Q6","device","TUP")
ElementSetAttr("Q6","manufacturer","unknown")
ElementSetAttr("Q6","manufacturer_part_number","unknown")
ElementSetAttr("Q6","vendor","unknown")
ElementSetAttr("Q6","vendor_part_number","unknown")
ChangePinName("Q6", 2, "B")
ChangePinName("Q6", 1, "C")
ChangePinName("Q6", 3, "E")
ElementList(Need,"Q5","TO92-1","BC547")
ElementSetAttr("Q5","device","TUN")
ElementSetAttr("Q5","manufacturer","unknown")
ElementSetAttr("Q5","manufacturer_part_number","unknown")
ElementSetAttr("Q5","vendor","unknown")
ElementSetAttr("Q5","vendor_part_number","unknown")
ChangePinName("Q5", 2, "B")
ChangePinName("Q5", 1, "E")
ChangePinName("Q5", 3, "C")
ElementList(Need,"R21","ACY300","10k")
ElementSetAttr("R21","device","RESISTOR")
ElementSetAttr("R21","manufacturer","unknown")
ElementSetAttr("R21","manufacturer_part_number","unknown")
ElementSetAttr("R21","vendor","unknown")
ElementSetAttr("R21","vendor_part_number","unknown")
ChangePinName("R21", 1, "1")
ChangePinName("R21", 2, "2")
ElementList(Need,"U1","DIP14","74HC14")
ElementSetAttr("U1","device","LOGIC_IC")
ElementSetAttr("U1","manufacturer","unknown")
ElementSetAttr("U1","manufacturer_part_number","unknown")
ElementSetAttr("U1","vendor","unknown")
ElementSetAttr("U1","vendor_part_number","unknown")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 1, "A")
ChangePinName("U1", 2, "B")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 5, "A")
ChangePinName("U1", 6, "B")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 3, "A")
ChangePinName("U1", 4, "B")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 9, "A")
ChangePinName("U1", 8, "B")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 11, "A")
ChangePinName("U1", 10, "B")
ChangePinName("U1", 7, "GND")
ChangePinName("U1", 14, "Vcc")
ChangePinName("U1", 13, "A")
ChangePinName("U1", 12, "B")
ElementList(Done)
